#!/usr/bin/env bash
# setup_keepass_snowbridge.sh — one-time macOS setup for KeePass access via
# the snowbridge SMB share.
#
# What this script does:
#   1. Verifies macOS and Homebrew prerequisites.
#   2. Installs keepassxc (provides keepassxc-cli) via Homebrew if missing.
#   3. Initialises config/keepass-snowbridge.env.local from the example if not
#      present, prompting for the snowbridge host and vault paths.
#   4. Stores the SMB password in macOS Keychain (never written to disk).
#   5. Writes or updates the auto-pass env file in the sibling auto-pass repo
#      with a profile entry for each configured vault.
#   6. Performs a test mount to verify connectivity.
#
# Run once; re-running is safe (skips steps that are already done).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
PORTFOLIO_ROOT="$(cd "${REPO_ROOT}/../.." && pwd)"
AUTO_PASS_ROOT="${PORTFOLIO_ROOT}/util-repos/auto-pass"

CONFIG_FILE="${REPO_ROOT}/config/keepass-snowbridge.env.local"
EXAMPLE_CONFIG="${REPO_ROOT}/config/keepass-snowbridge.example.env"

die()  { printf 'error: %s\n' "$*" >&2; exit 1; }
log()  { printf '\n[setup] %s\n' "$*"; }
info() { printf '  %s\n' "$*"; }
ask()  { printf '  %s: ' "$1" >&2; read -r REPLY; printf '%s' "${REPLY}"; }
ask_secret() { printf '  %s: ' "$1" >&2; read -rs REPLY; printf '\n' >&2; printf '%s' "${REPLY}"; }

# ── preflight ─────────────────────────────────────────────────────────────────

[[ "$(uname -s)" == "Darwin" ]] || die "this script is for macOS only"

command -v brew >/dev/null 2>&1 || die "Homebrew not found — install it from https://brew.sh first"

# ── 1. install keepassxc ──────────────────────────────────────────────────────

log "step 1/6 — keepassxc-cli"

if command -v keepassxc-cli >/dev/null 2>&1; then
    info "keepassxc-cli already installed: $(keepassxc-cli --version 2>&1 | head -1)"
else
    info "installing keepassxc via Homebrew (includes keepassxc-cli)..."
    brew install --cask keepassxc
    command -v keepassxc-cli >/dev/null 2>&1 \
        || die "keepassxc-cli not found after install — check your PATH for the KeePassXC.app bundle"
    info "installed: $(keepassxc-cli --version 2>&1 | head -1)"
fi

# ── 2. initialise local config ────────────────────────────────────────────────

log "step 2/6 — local config"

if [[ -f "${CONFIG_FILE}" ]]; then
    info "config already exists: ${CONFIG_FILE}"
    # shellcheck source=/dev/null
    source "${CONFIG_FILE}"
else
    info "creating ${CONFIG_FILE} from example..."
    cp "${EXAMPLE_CONFIG}" "${CONFIG_FILE}"

    printf '\n  Fill in the connection details below.\n'
    printf '  (Leave blank to keep the example value.)\n\n'

    SNOWBRIDGE_HOST="$(ask "snowbridge hostname or IP [snowbridge.local]")"
    SNOWBRIDGE_HOST="${SNOWBRIDGE_HOST:-snowbridge.local}"

    SNOWBRIDGE_SMB_USER="$(ask "Samba username [snowbridge]")"
    SNOWBRIDGE_SMB_USER="${SNOWBRIDGE_SMB_USER:-snowbridge}"

    SNOWBRIDGE_SMB_SHARE="$(ask "SMB share name [snowbridge]")"
    SNOWBRIDGE_SMB_SHARE="${SNOWBRIDGE_SMB_SHARE:-snowbridge}"

    SNOWBRIDGE_MOUNT_POINT="$(ask "local mount point [${HOME}/mnt/snowbridge]")"
    SNOWBRIDGE_MOUNT_POINT="${SNOWBRIDGE_MOUNT_POINT:-${HOME}/mnt/snowbridge}"

    printf '\n  KeePass vault paths relative to the share root.\n'
    printf '  Space-separate multiple vaults, e.g. "KeePass/personal.kdbx KeePass/work.kdbx"\n'
    KEEPASS_VAULT_SUBPATHS="$(ask "vault subpaths [KeePass/vault.kdbx]")"
    KEEPASS_VAULT_SUBPATHS="${KEEPASS_VAULT_SUBPATHS:-KeePass/vault.kdbx}"

    KEEPASS_AUTO_PASS_PROFILE_PREFIX="$(ask "auto-pass profile prefix [snowbridge]")"
    KEEPASS_AUTO_PASS_PROFILE_PREFIX="${KEEPASS_AUTO_PASS_PROFILE_PREFIX:-snowbridge}"

    # Rewrite config with filled values
    cat > "${CONFIG_FILE}" <<EOF
# KeePass-via-snowbridge — local config (gitignored).
# Generated by setup_keepass_snowbridge.sh on $(date '+%Y-%m-%d').

SNOWBRIDGE_HOST=${SNOWBRIDGE_HOST}
SNOWBRIDGE_SMB_USER=${SNOWBRIDGE_SMB_USER}
SNOWBRIDGE_SMB_SHARE=${SNOWBRIDGE_SMB_SHARE}
SNOWBRIDGE_MOUNT_POINT=${SNOWBRIDGE_MOUNT_POINT}
KEEPASS_VAULT_SUBPATHS="${KEEPASS_VAULT_SUBPATHS}"
KEEPASS_AUTO_PASS_PROFILE_PREFIX=${KEEPASS_AUTO_PASS_PROFILE_PREFIX}
EOF
    info "wrote ${CONFIG_FILE}"
fi

# Ensure all required vars are set after loading config
: "${SNOWBRIDGE_HOST:?}"
: "${SNOWBRIDGE_SMB_USER:?}"
: "${SNOWBRIDGE_SMB_SHARE:?}"
SNOWBRIDGE_MOUNT_POINT="${SNOWBRIDGE_MOUNT_POINT:-/Volumes/snowbridge}"
KEEPASS_VAULT_SUBPATHS="${KEEPASS_VAULT_SUBPATHS:-KeePass/vault.kdbx}"
KEEPASS_AUTO_PASS_PROFILE_PREFIX="${KEEPASS_AUTO_PASS_PROFILE_PREFIX:-snowbridge}"

# ── 3. store SMB credentials in macOS Keychain ────────────────────────────────

log "step 3/6 — macOS Keychain credential"

KEYCHAIN_EXISTING="$(
    security find-internet-password \
        -s "${SNOWBRIDGE_HOST}" \
        -a "${SNOWBRIDGE_SMB_USER}" \
        -w 2>/dev/null
)" || KEYCHAIN_EXISTING=

if [[ -n "${KEYCHAIN_EXISTING}" ]]; then
    info "Keychain entry already exists for ${SNOWBRIDGE_SMB_USER}@${SNOWBRIDGE_HOST}"
    printf '  Update it? [y/N]: '; read -r REPLY
    [[ "$(printf '%s' "${REPLY}" | tr '[:upper:]' '[:lower:]')" == "y" ]] || KEYCHAIN_EXISTING="keep"
fi

if [[ -z "${KEYCHAIN_EXISTING}" || "${KEYCHAIN_EXISTING}" != "keep" ]]; then
    SMB_PASSWORD="$(ask_secret "SMB password for ${SNOWBRIDGE_SMB_USER}@${SNOWBRIDGE_HOST}")"
    [[ -n "${SMB_PASSWORD}" ]] || die "password cannot be empty"

    security add-internet-password \
        -U \
        -s "${SNOWBRIDGE_HOST}" \
        -a "${SNOWBRIDGE_SMB_USER}" \
        -l "snowbridge SMB (${SNOWBRIDGE_SMB_SHARE})" \
        -w "${SMB_PASSWORD}"
    info "stored in Keychain"
fi

# ── 4. update auto-pass env file ──────────────────────────────────────────────

log "step 4/6 — auto-pass profiles"

AUTO_PASS_ENV_FILE="${AUTO_PASS_ROOT}/config/auto-pass.env.local"
AUTO_PASS_ENV_EXAMPLE="${AUTO_PASS_ROOT}/config/auto-pass.env.example"

if [[ ! -d "${AUTO_PASS_ROOT}" ]]; then
    info "auto-pass repo not found at ${AUTO_PASS_ROOT} — skipping (add profiles manually)"
else
    [[ -f "${AUTO_PASS_ENV_FILE}" ]] || {
        info "creating ${AUTO_PASS_ENV_FILE} from example..."
        cp "${AUTO_PASS_ENV_EXAMPLE}" "${AUTO_PASS_ENV_FILE}"
    }

    # Build profile blocks for each vault subpath
    idx=0
    PROFILE_LINES=()
    PROFILE_NAMES=()
    for subpath in ${KEEPASS_VAULT_SUBPATHS}; do
        if [[ ${idx} -eq 0 ]]; then
            profile_name="${KEEPASS_AUTO_PASS_PROFILE_PREFIX}"
        else
            profile_name="${KEEPASS_AUTO_PASS_PROFILE_PREFIX}_${idx}"
        fi
        profile_var="$(printf '%s' "${profile_name}" | tr '[:lower:]a-z-' '[:upper:]A-Z_')"
        vault_path="${SNOWBRIDGE_MOUNT_POINT}/${subpath}"

        PROFILE_NAMES+=("${profile_name}")
        PROFILE_LINES+=("AUTO_PASS_PROFILE_${profile_var}_KEEPASSXC_DB_PATH=${vault_path}")
        PROFILE_LINES+=("AUTO_PASS_PROFILE_${profile_var}_KEEPASSXC_DB_PASSWORD=")
        PROFILE_LINES+=("AUTO_PASS_PROFILE_${profile_var}_KEEPASSXC_KEY_FILE=")
        idx=$((idx + 1))
    done

    # Append a clearly delimited block so re-runs can be spotted
    BLOCK_MARKER="# --- snowbridge vaults (setup_keepass_snowbridge.sh) ---"
    if ! grep -qF "${BLOCK_MARKER}" "${AUTO_PASS_ENV_FILE}" 2>/dev/null; then
        {
            printf '\n%s\n' "${BLOCK_MARKER}"
            printf '# Vault password is entered interactively when auto-pass first opens the db.\n'
            printf '# Leave _DB_PASSWORD empty to be prompted; do NOT store the master password here.\n'
            for line in "${PROFILE_LINES[@]}"; do
                printf '%s\n' "${line}"
            done
        } >> "${AUTO_PASS_ENV_FILE}"
        info "appended $(printf '%s\n' "${PROFILE_NAMES[@]}" | tr '\n' ' ')profiles to ${AUTO_PASS_ENV_FILE}"
    else
        info "snowbridge block already present in ${AUTO_PASS_ENV_FILE}"
    fi

    info "to use a vault:  cd ${AUTO_PASS_ROOT} && auto-pass --profile ${PROFILE_NAMES[0]} ls /"
fi

# ── 5. gitignore the local config ─────────────────────────────────────────────

log "step 5/6 — gitignore"

GITIGNORE="${REPO_ROOT}/.gitignore"
IGNORE_PATTERN="config/keepass-snowbridge.env.local"

if [[ -f "${GITIGNORE}" ]] && grep -qF "${IGNORE_PATTERN}" "${GITIGNORE}"; then
    info "already in .gitignore"
else
    printf '%s\n' "${IGNORE_PATTERN}" >> "${GITIGNORE}"
    info "added ${IGNORE_PATTERN} to .gitignore"
fi

# ── 6. test mount ─────────────────────────────────────────────────────────────

log "step 6/6 — test mount"

printf '  Attempt a test mount now? [Y/n]: '; read -r REPLY
if [[ "$(printf '%s' "${REPLY}" | tr '[:upper:]' '[:lower:]')" != "n" ]]; then
    bash "${SCRIPT_DIR}/mount_snowbridge.sh"
    printf '\n  Test mount succeeded.\n'
    printf '  Unmount with:  bash scripts/unmount_snowbridge.sh\n'
    printf '  Remount with:  bash scripts/mount_snowbridge.sh\n'
else
    info "skipped — run 'bash scripts/mount_snowbridge.sh' when ready"
fi

printf '\n[setup] done\n\n'
printf 'Quick reference:\n'
printf '  mount   bash scripts/mount_snowbridge.sh\n'
printf '  unmount bash scripts/unmount_snowbridge.sh\n'
printf '  remote  bash scripts/mount_snowbridge.sh --host <vpn-ip>\n'
if [[ -d "${AUTO_PASS_ROOT}" ]]; then
    printf '  vault   cd %s && auto-pass --profile %s ls /\n' \
        "${AUTO_PASS_ROOT}" "${PROFILE_NAMES[0]:-snowbridge}"
fi
